version: '2'
services:
  datastore:
    image: busybox
    volumes:
      - bundle_install:/usr/local/bundle
      - node_modules:/hanami-webpack-sample/node_modules
      - postgres:/var/lib/postgresql/data
  postgres:
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    ports:
      - "5431:5432"
    volumes_from:
      - datastore
  app:
    build: .
    tty: true
    stdin_open: true
    command: bundle exec hanami server
    env_file:
      - .env.development
    environment:
      - PGHOST=postgres
      - PGPORT=5431
      - PGUSER=postgres
      - PGPASSWORD=password
      - INBUILT_WEBPACK_DEV_SERVER=true
      - WEBPACK_DEV_SERVER_PORT=3020
      - HANAMI_HOST=0.0.0.0
      - HANAMI_PORT=3000
    volumes_from:
      - datastore
    volumes:
      - .:/hanami-webpack-sample
    ports:
      - "3000:3000"
      - "3020:3020"
    depends_on:
      - postgres

volumes:
  bundle_install:
    driver: local
  node_modules:
    driver: local
  postgres:
    driver: local
